# Generated by Django 3.2 on 2021-04-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_authenticated', models.BooleanField(blank=True, default=False, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=25, null=True)),
                ('session_type', models.CharField(blank=True, max_length=50, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('key', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('account_password', models.CharField(blank=True, max_length=100, null=True)),
                ('public_key', models.CharField(blank=True, max_length=150, null=True)),
                ('private_key', models.CharField(blank=True, max_length=150, null=True)),
                ('execution_port', models.IntegerField(blank=True, null=True)),
                ('account_port', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(blank=True, max_length=25, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=150)),
                ('order_state', models.CharField(blank=True, choices=[('INIT', 'INIT'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('FILLED', 'FILLED')], max_length=6, null=True)),
                ('init_time', models.CharField(blank=True, max_length=25, null=True)),
                ('symbol', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('side', models.CharField(blank=True, choices=[('B', 'BUY'), ('S', 'SELL')], max_length=1, null=True)),
                ('order_type', models.CharField(blank=True, choices=[('L', 'LIMIT'), ('M', 'MARKET')], max_length=1, null=True)),
                ('quote', models.CharField(blank=True, max_length=100, null=True)),
                ('meta', models.CharField(blank=True, max_length=100, null=True)),
                ('hash', models.CharField(blank=True, max_length=100, null=True)),
                ('init_id', models.CharField(blank=True, max_length=100, null=True)),
                ('open_id', models.CharField(blank=True, max_length=100, null=True)),
                ('filled_id', models.CharField(blank=True, max_length=100, null=True)),
                ('closed_id', models.CharField(blank=True, max_length=100, null=True)),
                ('open_time', models.CharField(blank=True, max_length=25, null=True)),
                ('closed_time', models.CharField(blank=True, max_length=25, null=True)),
                ('order_number', models.CharField(blank=True, max_length=25, null=True)),
                ('orders_filled', models.FloatField(blank=True, null=True)),
                ('orders_remaining', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=150)),
                ('position_state', models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], max_length=6, null=True)),
                ('symbol', models.CharField(blank=True, max_length=30, null=True)),
                ('quote', models.CharField(blank=True, max_length=100, null=True)),
                ('meta', models.CharField(blank=True, max_length=100, null=True)),
                ('side', models.CharField(blank=True, choices=[('B', 'BUY'), ('S', 'SELL')], max_length=1, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('average_price', models.FloatField(blank=True, null=True)),
                ('invest_amount', models.FloatField(blank=True, null=True)),
                ('borrow_amount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('code_list', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
