# Generated by Django 3.2 on 2021-04-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('code_list', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universe', to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='db.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=150)),
                ('position_state', models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], max_length=6, null=True)),
                ('symbol', models.CharField(blank=True, max_length=30, null=True)),
                ('meta', models.CharField(blank=True, max_length=100, null=True)),
                ('side', models.CharField(blank=True, choices=[('B', 'BUY'), ('S', 'SELL')], max_length=1, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('average_price', models.FloatField(blank=True, null=True)),
                ('invest_amount', models.FloatField(blank=True, null=True)),
                ('borrow_amount', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=150)),
                ('order_state', models.CharField(blank=True, choices=[('INIT', 'INIT'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('FILLED', 'FILLED')], max_length=6, null=True)),
                ('init_time', models.CharField(blank=True, max_length=25, null=True)),
                ('symbol', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('side', models.CharField(blank=True, choices=[('B', 'BUY'), ('S', 'SELL')], max_length=1, null=True)),
                ('order_type', models.CharField(blank=True, choices=[('L', 'LIMIT'), ('M', 'MARKET')], max_length=1, null=True)),
                ('meta', models.CharField(blank=True, max_length=100, null=True)),
                ('hash', models.CharField(blank=True, max_length=100, null=True)),
                ('init_id', models.CharField(blank=True, max_length=100, null=True)),
                ('open_id', models.CharField(blank=True, max_length=100, null=True)),
                ('filled_id', models.CharField(blank=True, max_length=100, null=True)),
                ('open_time', models.CharField(blank=True, max_length=25, null=True)),
                ('order_number', models.CharField(blank=True, max_length=25, null=True)),
                ('orders_filled', models.FloatField(blank=True, null=True)),
                ('orders_remaining', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(blank=True, max_length=25, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_history', to='db.order')),
            ],
        ),
    ]
