# Generated by Django 3.2 on 2021-04-21 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('db', '0002_blogimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(blank=True, max_length=25, null=True)),
                ('is_authenticated', models.BooleanField(blank=True, default=False, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='user.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
