# Generated by Django 3.2 on 2021-04-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20210421_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='closed_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='closed_time',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
