# Generated by Django 3.2 on 2021-04-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20210421_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='quote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
